version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    container_name: product_test-app
    volumes:
      - /home/vitaly/projects/product_test:/var/www/html
    environment:
      PHP_IDE_CONFIG: serverName=product_test-docker
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: catalog
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:80"
      - "9003:9003" # Xdebug
      - "5173:5173" # Vite dev-сервер
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: product_test-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
